# Generated by Django 5.2 on 2026-04-07 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imatge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arxiu', models.ImageField(upload_to='imatges/')),
                ('desc', models.TextField(blank=True, null=True)),
                ('llibre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.llibre')),
            ],
        ),
    ]
